# docker-compose.yml
version: '3'
services:
  app:
    env_file: .env
    build: .
    depends_on:
      - db
    ports:
      - '4000:4000'

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
