# docker-compose.yml
version: '3'
name: youtube-sharing-app
services:
  be:
    container_name: be
    env_file: .env
    image: youtube-sharing-app-be:latest
    volumes:
      - ./:/home/app
      - node_modules:/home/app/node_modules
      - dist:/home/app/dist
    depends_on:
      - db
    ports:
      - '4000:4000'

  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: youtube-sharing-app-nginx:latest
    tty: true
    depends_on:
      - be
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

volumes:
  db:
    driver: local
  node_modules:
    driver: local
  dist:
