# docker-compose.yml
version: '3'
name: youtube-sharing-app
services:
  be:
    container_name: be
    env_file: .env
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
      - node_modules_be:/home/app/node_modules
    depends_on:
      - db
    ports:
      - '4000:4000'
    networks:
      - ysa

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - ysa

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx
    tty: true
    depends_on:
      - be
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ysa

networks:
  ysa:
    driver: bridge

volumes:
  db:
    driver: local
  node_modules_be:
    driver: local
